@base_url = http://127.0.0.1:8080/

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJsdW1lbi1qd3QiLCJzdWIiOjQsImlhdCI6MTU2MTA5OTg4OCwiZXhwIjoxNTYxMTAzNDg4fQ.K58kw04rAXKr9KvP0Q9WCM7-bABWaeDcZx1R2WyQ4Gs

### login
POST {{base_url}}auth/login
Content-Type: application/x-www-form-urlencoded

email=amaya02@gmail.com
&password=12345

### get products
GET {{base_url}}products?token={{token}}

### post products
POST {{base_url}}api/products?token={{token}}
Content-Type: application/x-www-form-urlencoded

sku=qwerty
&name=jaket
&category=apparel
&description=lorem ipsum dolor sit amet
&regular_price=1234
&discount_price=222
&quantity=100
&taxable=1
&weight=1
